package com.ics.ics_hc_offline.database.helpers;

import android.annotation.SuppressLint;
import android.content.ContentValues;
import android.database.Cursor;

import com.ics.ics_hc_offline.database.constants.MainDBConstants;
import com.ics.ics_hc_offline.dto.ExpedienteDTO;
import com.ics.ics_hc_offline.dto.HojaConsultaOffLineDTO;
import com.ics.ics_hc_offline.dto.InicioDTO;

import net.sqlcipher.database.SQLiteStatement;

public class HojaConsultaHelper extends BindStatementHelper {
    @SuppressLint("Range")
    public static HojaConsultaOffLineDTO crearHojaConsulta(Cursor cursorHojaConsulta) {
        HojaConsultaOffLineDTO mHojaConsulta = new HojaConsultaOffLineDTO();
        mHojaConsulta.setSecHojaConsulta(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.secHojaConsulta)));
        mHojaConsulta.setCodExpediente(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.codExpediente)));
        mHojaConsulta.setNumHojaConsulta(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.numHojaConsulta)));
        mHojaConsulta.setNumOrdenLlegada(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.ordenLlegada)));
        mHojaConsulta.setEstado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.estado)));
        mHojaConsulta.setFechaConsulta(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaConsulta)));
        mHojaConsulta.setPesoKg(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.pesoKg)));
        mHojaConsulta.setTallaCm(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.tallaCm)));
        mHojaConsulta.setTemperaturac(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.temperaturac)));
        mHojaConsulta.setUsuarioEnfermeria(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.usuarioEnfermeria)));
        mHojaConsulta.setExpedienteFisico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.expedienteFisico)));
        mHojaConsulta.setHistoriaExamenFisico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.historiaExamenFisico)));
        mHojaConsulta.setPlanes(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.planes)));
        mHojaConsulta.setPresion(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.presion)));
        mHojaConsulta.setPas(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.pas)));
        mHojaConsulta.setPad(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.pad)));
        mHojaConsulta.setFciaResp(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.fciaResp)));
        mHojaConsulta.setFciaCard(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.fciaCard)));
        mHojaConsulta.setLugarAtencion(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.lugarAtencion)));
        mHojaConsulta.setConsulta(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.consulta)));
        mHojaConsulta.setSegChick(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.segChick)));
        mHojaConsulta.setTurno(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.turno)));
        mHojaConsulta.setTemMedc(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.temMedc)));
        mHojaConsulta.setFis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fis)));
        mHojaConsulta.setFif(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fif)));
        mHojaConsulta.setUltDiaFiebre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ultDiaFiebre)));
        mHojaConsulta.setUltDosisAntipiretico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ultDosisAntipiretico)));
        mHojaConsulta.setAmPmUltDiaFiebre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.amPmUltDiaFiebre)));
        mHojaConsulta.setHoraUltDosisAntipiretico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.horaUltDosisAntipiretico)));
        mHojaConsulta.setAmPmUltDosisAntipiretico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.amPmUltDosisAntipiretico)));
        mHojaConsulta.setFiebre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fiebre)));
        mHojaConsulta.setAstenia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.astenia)));
        mHojaConsulta.setAsomnoliento(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.asomnoliento)));
        mHojaConsulta.setMalEstado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.malEstado)));
        mHojaConsulta.setPerdidaConsciencia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.perdidaConsciencia)));
        mHojaConsulta.setInquieto(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.inquieto)));
        mHojaConsulta.setConvulsiones(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.convulsiones)));
        mHojaConsulta.setHipotermia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hipotermia)));
        mHojaConsulta.setLetargia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.letargia)));
        mHojaConsulta.setPocoApetito(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.pocoApetito)));
        mHojaConsulta.setNausea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.nausea)));
        mHojaConsulta.setDificultadAlimentarse(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dificultadAlimentarse)));
        mHojaConsulta.setVomito12horas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.vomito12horas)));
        mHojaConsulta.setVomito12h(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.vomito12h)));
        mHojaConsulta.setDiarrea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.diarrea)));
        mHojaConsulta.setDiarreaSangre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.diarreaSangre)));
        mHojaConsulta.setEstrenimiento(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.estrenimiento)));
        mHojaConsulta.setDolorAbIntermitente(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dolorAbIntermitente)));
        mHojaConsulta.setDolorAbContinuo(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dolorAbContinuo)));
        mHojaConsulta.setEpigastralgia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.epigastralgia)));
        mHojaConsulta.setIntoleranciaOral(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.intoleranciaOral)));
        mHojaConsulta.setDistensionAbdominal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.distensionAbdominal)));
        mHojaConsulta.setHepatomegalia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hepatomegalia)));
        mHojaConsulta.setHepatomegaliaCm(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.hepatomegaliaCm)));
        mHojaConsulta.setAltralgia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.altralgia)));
        mHojaConsulta.setMialgia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.mialgia)));
        mHojaConsulta.setLumbalgia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.lumbalgia)));
        mHojaConsulta.setDolorCuello(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dolorCuello)));
        mHojaConsulta.setTenosinovitis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.tenosinovitis)));
        mHojaConsulta.setArtralgiaProximal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.artralgiaProximal)));
        mHojaConsulta.setArtralgiaDistal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.artralgiaDistal)));
        mHojaConsulta.setConjuntivitis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.conjuntivitis)));
        mHojaConsulta.setEdemaMunecas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.edemaMunecas)));
        mHojaConsulta.setEdemaCodos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.edemaCodos)));
        mHojaConsulta.setEdemaHombros(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.edemaHombros)));
        mHojaConsulta.setEdemaRodillas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.edemaRodillas)));
        mHojaConsulta.setEdemaTobillos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.edemaTobillos)));
        mHojaConsulta.setCefalea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cefalea)));
        mHojaConsulta.setRigidezCuello(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rigidezCuello)));
        mHojaConsulta.setInyeccionConjuntival(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.inyeccionConjuntival)));
        mHojaConsulta.setHemorragiaSuconjuntival(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hemorragiaSuconjuntival)));
        mHojaConsulta.setDolorRetroocular(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dolorRetroocular)));
        mHojaConsulta.setFontanelaAbombada(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fontanelaAbombada)));
        mHojaConsulta.setIctericiaConuntival(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ictericiaConuntival)));
        mHojaConsulta.setLenguaMucosasSecas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.lenguaMucosasSecas)));
        mHojaConsulta.setPliegueCutaneo(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.pliegueCutaneo)));
        mHojaConsulta.setOrinaReducida(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.orinaReducida)));
        mHojaConsulta.setBebeConSed(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bebeConSed)));
        mHojaConsulta.setOjosHundidos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ojosHundidos)));
        mHojaConsulta.setFontanelaHundida(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fontanelaHundida)));
        mHojaConsulta.setRahsLocalizado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rahsLocalizado)));
        mHojaConsulta.setRahsGeneralizado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rahsGeneralizado)));
        mHojaConsulta.setRashEritematoso(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rashEritematoso)));
        mHojaConsulta.setRahsMacular(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rahsMacular)));
        mHojaConsulta.setRashPapular(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rashPapular)));
        mHojaConsulta.setRahsMoteada(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rahsMoteada)));
        mHojaConsulta.setRuborFacial(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ruborFacial)));
        mHojaConsulta.setEquimosis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.equimosis)));
        mHojaConsulta.setCianosisCentral(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cianosisCentral)));
        mHojaConsulta.setIctericia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ictericia)));
        mHojaConsulta.setEritema(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.eritema)));
        mHojaConsulta.setDolorGarganta(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dolorGarganta)));
        mHojaConsulta.setAdenopatiasCervicales(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.adenopatiasCervicales)));
        mHojaConsulta.setExudado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.exudado)));
        mHojaConsulta.setPetequiasMucosa(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.petequiasMucosa)));
        mHojaConsulta.setSintomasUrinarios(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sintomasUrinarios)));
        mHojaConsulta.setLeucocituria(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.leucocituria)));
        mHojaConsulta.setNitritos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.nitritos)));
        mHojaConsulta.setEritrocitos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.eritrocitos)));
        mHojaConsulta.setBilirrubinuria(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bilirrubinuria)));
        mHojaConsulta.setObeso(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.obeso)));
        mHojaConsulta.setSobrepeso(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sobrepeso)));
        mHojaConsulta.setSospechaProblema(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sospechaProblema)));
        mHojaConsulta.setNormal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.normal)));
        mHojaConsulta.setBajoPeso(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bajoPeso)));
        mHojaConsulta.setBajoPesoSevero(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bajoPesoSevero)));
        mHojaConsulta.setTos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.tos)));
        mHojaConsulta.setRinorrea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.rinorrea)));
        mHojaConsulta.setCongestionNasal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.congestionNasal)));
        mHojaConsulta.setOtalgia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otalgia)));
        mHojaConsulta.setAleteoNasal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.aleteoNasal)));
        mHojaConsulta.setApnea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.apnea)));
        mHojaConsulta.setRespiracionRapida(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.respiracionRapida)));
        mHojaConsulta.setQuejidoEspiratorio(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.quejidoEspiratorio)));
        mHojaConsulta.setEstiradorReposo(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.estiradorReposo)));
        mHojaConsulta.setTirajeSubcostal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.tirajeSubcostal)));
        mHojaConsulta.setSibilancias(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sibilancias)));
        mHojaConsulta.setCrepitos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.crepitos)));
        mHojaConsulta.setRoncos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.roncos)));
        mHojaConsulta.setOtraFif(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otraFif)));
        mHojaConsulta.setNuevaFif(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.nuevaFif)));
        mHojaConsulta.setInterconsultaPediatrica(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.interconsultaPediatrica)));
        mHojaConsulta.setReferenciaHospital(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.referenciaHospital)));
        mHojaConsulta.setReferenciaDengue(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.referenciaDengue)));
        mHojaConsulta.setReferenciaIrag(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.referenciaIrag)));
        mHojaConsulta.setReferenciaChik(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.referenciaChik)));
        mHojaConsulta.setEti(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.eti)));
        mHojaConsulta.setIrag(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.irag)));
        mHojaConsulta.setNeumonia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.neumonia)));
        mHojaConsulta.setLactanciaMaterna(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.lactanciaMaterna)));
        mHojaConsulta.setVacunasCompletas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.vacunasCompletas)));
        mHojaConsulta.setVacunaInfluenza(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.vacunaInfluenza)));
        mHojaConsulta.setFechaVacuna(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaVacuna)));
        mHojaConsulta.setSaturaciono2(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.saturaciono2)));
        mHojaConsulta.setImc(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.imc)));
        mHojaConsulta.setCategoria(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.categoria)));
        mHojaConsulta.setCambioCategoria(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cambioCategoria)));
        mHojaConsulta.setManifestacionHemorragica(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.manifestacionHemorragica)));
        mHojaConsulta.setPruebaTorniquetePositiva(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.pruebaTorniquetePositiva)));
        mHojaConsulta.setPetequia10Pt(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.petequia10Pt)));
        mHojaConsulta.setPetequia20Pt(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.petequia20Pt)));
        mHojaConsulta.setPielExtremidadesFrias(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.pielExtremidadesFrias)));
        mHojaConsulta.setPalidezEnExtremidades(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.palidezEnExtremidades)));
        mHojaConsulta.setEpistaxis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.epistaxis)));
        mHojaConsulta.setGingivorragia(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.gingivorragia)));
        mHojaConsulta.setPetequiasEspontaneas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.petequiasEspontaneas)));
        mHojaConsulta.setLlenadoCapilar2seg(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.llenadoCapilar2seg)));
        mHojaConsulta.setCianosis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cianosis)));
        mHojaConsulta.setLinfocitosaAtipicos(cursorHojaConsulta.getDouble(cursorHojaConsulta.getColumnIndex(MainDBConstants.linfocitosaAtipicos)));
        mHojaConsulta.setFechaLinfocitos(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaLinfocitos)));
        mHojaConsulta.setHipermenorrea(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hipermenorrea)));
        mHojaConsulta.setHematemesis(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hematemesis)));
        mHojaConsulta.setMelena(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.melena)));
        mHojaConsulta.setHemoconc(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hemoconc)));
        mHojaConsulta.setHemoconcentracion(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.hemoconcentracion)));
        mHojaConsulta.setHospitalizado(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hospitalizado)));
        mHojaConsulta.setHospitalizadoEspecificar(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hospitalizadoEspecificar)));
        mHojaConsulta.setTransfusionSangre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.transfusionSangre)));
        mHojaConsulta.setTransfusionEspecificar(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.transfusionEspecificar)));
        mHojaConsulta.setTomandoMedicamento(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.tomandoMedicamento)));
        mHojaConsulta.setMedicamentoDistEspecificar(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.medicamentoDistEspecificar)));
        mHojaConsulta.setMedicamentoDistinto(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.medicamentoDistinto)));
        mHojaConsulta.setMedicamentoDistEspecificar(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.medicamentoDistEspecificar)));
        mHojaConsulta.setHorasv(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.horasv)));
        mHojaConsulta.setAcetaminofen(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.acetaminofen)));
        mHojaConsulta.setAsa(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.asa)));
        mHojaConsulta.setIbuprofen(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ibuprofen)));
        mHojaConsulta.setPenicilina(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.penicilina)));
        mHojaConsulta.setAmoxicilina(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.amoxicilina)));
        mHojaConsulta.setDicloxacilina(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.dicloxacilina)));
        mHojaConsulta.setOtroAntibiotico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otroAntibiotico)));
        mHojaConsulta.setFurazolidona(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.furazolidona)));
        mHojaConsulta.setMetronidazolTinidazol(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.metronidazolTinidazol)));
        mHojaConsulta.setAlbendazolMebendazol(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.albendazolMebendazol)));
        mHojaConsulta.setSulfatoFerroso(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sulfatoFerroso)));
        mHojaConsulta.setSueroOral(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sueroOral)));
        mHojaConsulta.setSulfatoZinc(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.sulfatoZinc)));
        mHojaConsulta.setLiquidosIv(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.liquidosIv)));
        mHojaConsulta.setPrednisona(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.prednisona)));
        mHojaConsulta.setHidrocortisonaIv(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hidrocortisonaIv)));
        mHojaConsulta.setSalbutamol(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.salbutamol)));
        mHojaConsulta.setOseltamivir(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.oseltamivir)));
        mHojaConsulta.setTelef(cursorHojaConsulta.getLong(cursorHojaConsulta.getColumnIndex(MainDBConstants.telef)));
        mHojaConsulta.setProximaCita(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.proximaCita)));
        mHojaConsulta.setHorarioClases(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.horarioClases)));
        mHojaConsulta.setColegio(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.colegio)));
        mHojaConsulta.setBhc(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bhc)));
        mHojaConsulta.setSerologiaDengue(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.serologiaDengue)));
        mHojaConsulta.setSerologiaChik(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.serologiaChik)));
        mHojaConsulta.setGotaGruesa(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.gotaGruesa)));
        mHojaConsulta.setExtendidoPeriferico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.extendidoPeriferico)));
        mHojaConsulta.setEgo(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.ego)));
        mHojaConsulta.setEgh(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.egh)));
        mHojaConsulta.setCitologiaFecal(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.citologiaFecal)));
        mHojaConsulta.setFactorReumatoideo(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.factorReumatoideo)));
        mHojaConsulta.setAlbumina(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.albumina)));
        mHojaConsulta.setAstAlt(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.astAlt)));
        mHojaConsulta.setBilirrubinas(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.bilirrubinas)));
        mHojaConsulta.setCpk(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cpk)));
        mHojaConsulta.setColesterol(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.colesterol)));
        mHojaConsulta.setInfluenza(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.influenza)));
        mHojaConsulta.setOtroExamenLab(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otroExamenLab)));
        mHojaConsulta.setOel(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.oel)));
        mHojaConsulta.setNumOrdenLaboratorio(cursorHojaConsulta.getInt(cursorHojaConsulta.getColumnIndex(MainDBConstants.numOrdenLaboratorio)));
        mHojaConsulta.setFechaOrdenLaboratorio(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaOrdenLaboratorio)));
        mHojaConsulta.setDiagnostico1(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.diagnostico1)));
        mHojaConsulta.setDiagnostico2(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.diagnostico2)));
        mHojaConsulta.setDiagnostico3(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.diagnostico3)));
        mHojaConsulta.setDiagnostico4(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.diagnostico4)));
        mHojaConsulta.setOtroDiagnostico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otroDiagnostico)));
        mHojaConsulta.setFechaCierre(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaCierre)));
        mHojaConsulta.setFechaCambioTurno(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaCambioTurno)));
        mHojaConsulta.setFechaCierreCambioTurno(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.fechaCierreCambioTurno)));
        mHojaConsulta.setUsuarioMedico(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.usuarioMedico)));
        mHojaConsulta.setMedicoCambioTurno(cursorHojaConsulta.getShort(cursorHojaConsulta.getColumnIndex(MainDBConstants.medicoCambioTurno)));
        mHojaConsulta.setOtro(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.otro)));
        mHojaConsulta.setEstudiosParticipantes(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.estudiosParticipantes)));
        mHojaConsulta.setcV(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.cV)));
        mHojaConsulta.setConsultaRespiratorio(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.consultaRespiratorio)));
        mHojaConsulta.setEsConsultaTerreno(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.esConsultaTerreno)));
        mHojaConsulta.setEstadoCarga(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.estadoCarga)));
        mHojaConsulta.setHora(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.hora)));
        mHojaConsulta.setNoAtiendeLlamadoEnfermeria(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.noAtiendeLlamadoEnfermeria)));
        mHojaConsulta.setNoAtiendeLlamadoMedico(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.noAtiendeLlamadoMedico)));
        mHojaConsulta.setMedicamentoEspecificar(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.medicamentoEspecificar)));
        mHojaConsulta.setStatusSubmitted(cursorHojaConsulta.getString(cursorHojaConsulta.getColumnIndex(MainDBConstants.statusSubmitted)));
        return mHojaConsulta;
    }

    public static void fillHojaConsultaStatement(SQLiteStatement stat, HojaConsultaOffLineDTO hojaConsultaDTO){
        bindInteger(stat, 1, hojaConsultaDTO.getSecHojaConsulta());
        bindInteger(stat, 2, hojaConsultaDTO.getCodExpediente());
        bindInteger(stat, 3, hojaConsultaDTO.getNumHojaConsulta());
        bindInteger(stat, 4, hojaConsultaDTO.getNumOrdenLlegada());
        bindString(stat, 5, String.valueOf(hojaConsultaDTO.getEstado()));
        bindString(stat, 6, hojaConsultaDTO.getFechaConsulta());
        stat.bindDouble(7, hojaConsultaDTO.getPesoKg());
        stat.bindDouble(8, hojaConsultaDTO.getTallaCm());
        stat.bindDouble(9, hojaConsultaDTO.getTemperaturac());
        bindInteger(stat, 10, hojaConsultaDTO.getUsuarioEnfermeria());
        bindString(stat, 11, hojaConsultaDTO.getExpedienteFisico());
        bindString(stat, 12, hojaConsultaDTO.getHistoriaExamenFisico());
        bindString(stat, 13, hojaConsultaDTO.getPlanes());
        bindString(stat, 14, hojaConsultaDTO.getPresion()); //Dato siempre a estado null
        bindString(stat, 15, String.valueOf(hojaConsultaDTO.getPas())); // Revisar jaja
        bindString(stat, 16, String.valueOf(hojaConsultaDTO.getPad()));
        bindInteger(stat, 17, hojaConsultaDTO.getFciaResp());
        bindInteger(stat, 18, hojaConsultaDTO.getFciaCard());
        bindString(stat, 19, hojaConsultaDTO.getLugarAtencion());
        bindString(stat, 20, hojaConsultaDTO.getConsulta());
        bindString(stat, 21, hojaConsultaDTO.getSegChick());
        bindString(stat, 22, hojaConsultaDTO.getTurno());
        bindString(stat, 23, String.valueOf(hojaConsultaDTO.getTemMedc())); // Revisar jaja
        bindString(stat, 24, hojaConsultaDTO.getFis());
        bindString(stat, 25, hojaConsultaDTO.getFif());
        bindString(stat, 26, hojaConsultaDTO.getUltDiaFiebre());
        bindString(stat, 27, hojaConsultaDTO.getUltDosisAntipiretico());
        bindString(stat, 28, hojaConsultaDTO.getAmPmUltDiaFiebre());
        bindString(stat, 29, hojaConsultaDTO.getHoraUltDosisAntipiretico());
        bindString(stat, 30, hojaConsultaDTO.getAmPmUltDosisAntipiretico());
        bindString(stat, 31, String.valueOf(hojaConsultaDTO.getFiebre()));
        bindString(stat, 32, String.valueOf(hojaConsultaDTO.getAstenia()));
        bindString(stat, 33, String.valueOf(hojaConsultaDTO.getAsomnoliento()));
        bindString(stat, 34, String.valueOf(hojaConsultaDTO.getMalEstado()));
        bindString(stat, 35, String.valueOf(hojaConsultaDTO.getPerdidaConsciencia()));
        bindString(stat, 36, String.valueOf(hojaConsultaDTO.getInquieto()));
        bindString(stat, 37, String.valueOf(hojaConsultaDTO.getConvulsiones()));
        bindString(stat, 38, String.valueOf(hojaConsultaDTO.getHipotermia()));
        bindString(stat, 39, String.valueOf(hojaConsultaDTO.getLetargia()));
        bindString(stat, 40, String.valueOf(hojaConsultaDTO.getPocoApetito()));
        bindString(stat, 41, String.valueOf(hojaConsultaDTO.getNausea()));
        bindString(stat, 42, String.valueOf(hojaConsultaDTO.getDificultadAlimentarse()));
        bindString(stat, 43, String.valueOf(hojaConsultaDTO.getVomito12horas()));
        bindString(stat, 44, String.valueOf(hojaConsultaDTO.getVomito12h()));
        bindString(stat, 45, String.valueOf(hojaConsultaDTO.getDiarrea()));
        bindString(stat, 46, String.valueOf(hojaConsultaDTO.getDiarreaSangre()));
        bindString(stat, 47, String.valueOf(hojaConsultaDTO.getEstrenimiento()));
        bindString(stat, 48, String.valueOf(hojaConsultaDTO.getDolorAbIntermitente()));
        bindString(stat, 49, String.valueOf(hojaConsultaDTO.getDolorAbContinuo()));
        bindString(stat, 50, String.valueOf(hojaConsultaDTO.getEpigastralgia()));
        bindString(stat, 51, String.valueOf(hojaConsultaDTO.getIntoleranciaOral()));
        bindString(stat, 52, String.valueOf(hojaConsultaDTO.getDistensionAbdominal()));
        bindString(stat, 53, String.valueOf(hojaConsultaDTO.getHepatomegalia()));
        bindString(stat, 54, String.valueOf(hojaConsultaDTO.getHepatomegaliaCm()));
        bindString(stat, 55, String.valueOf(hojaConsultaDTO.getAltralgia()));
        bindString(stat, 56, String.valueOf(hojaConsultaDTO.getMialgia()));
        bindString(stat, 57, String.valueOf(hojaConsultaDTO.getLumbalgia()));
        bindString(stat, 58, String.valueOf(hojaConsultaDTO.getDolorCuello()));
        bindString(stat, 59, String.valueOf(hojaConsultaDTO.getTenosinovitis()));
        bindString(stat, 60, String.valueOf(hojaConsultaDTO.getArtralgiaProximal()));
        bindString(stat, 61, String.valueOf(hojaConsultaDTO.getArtralgiaDistal()));
        bindString(stat, 62, String.valueOf(hojaConsultaDTO.getConjuntivitis()));
        bindString(stat, 63, String.valueOf(hojaConsultaDTO.getEdemaMunecas()));
        bindString(stat, 64, String.valueOf(hojaConsultaDTO.getEdemaCodos()));
        bindString(stat, 65, String.valueOf(hojaConsultaDTO.getEdemaHombros()));
        bindString(stat, 66, String.valueOf(hojaConsultaDTO.getEdemaRodillas()));
        bindString(stat, 67, String.valueOf(hojaConsultaDTO.getEdemaTobillos()));
        bindString(stat, 68, String.valueOf(hojaConsultaDTO.getCefalea()));
        bindString(stat, 69, String.valueOf(hojaConsultaDTO.getRigidezCuello()));
        bindString(stat, 70, String.valueOf(hojaConsultaDTO.getInyeccionConjuntival()));
        bindString(stat, 71, String.valueOf(hojaConsultaDTO.getHemorragiaSuconjuntival()));
        bindString(stat, 72, String.valueOf(hojaConsultaDTO.getDolorRetroocular()));
        bindString(stat, 73, String.valueOf(hojaConsultaDTO.getFontanelaAbombada()));
        bindString(stat, 74, String.valueOf(hojaConsultaDTO.getIctericiaConuntival()));
        bindString(stat, 75, String.valueOf(hojaConsultaDTO.getLenguaMucosasSecas()));
        bindString(stat, 76, String.valueOf(hojaConsultaDTO.getPliegueCutaneo()));
        bindString(stat, 77, String.valueOf(hojaConsultaDTO.getOrinaReducida()));
        bindString(stat, 78, String.valueOf(hojaConsultaDTO.getBebeConSed()));
        bindString(stat, 79, String.valueOf(hojaConsultaDTO.getOjosHundidos()));
        bindString(stat, 80, String.valueOf(hojaConsultaDTO.getFontanelaHundida()));
        bindString(stat, 81, String.valueOf(hojaConsultaDTO.getRahsLocalizado()));
        bindString(stat, 82, String.valueOf(hojaConsultaDTO.getRahsGeneralizado()));
        bindString(stat, 83, String.valueOf(hojaConsultaDTO.getRashEritematoso()));
        bindString(stat, 84, String.valueOf(hojaConsultaDTO.getRahsMacular()));
        bindString(stat, 85, String.valueOf(hojaConsultaDTO.getRashPapular()));
        bindString(stat, 86, String.valueOf(hojaConsultaDTO.getRahsMoteada()));
        bindString(stat, 87, String.valueOf(hojaConsultaDTO.getRuborFacial()));
        bindString(stat, 88, String.valueOf(hojaConsultaDTO.getEquimosis()));
        bindString(stat, 89, String.valueOf(hojaConsultaDTO.getCianosisCentral()));
        bindString(stat, 90, String.valueOf(hojaConsultaDTO.getIctericia()));
        bindString(stat, 91, String.valueOf(hojaConsultaDTO.getEritema()));
        bindString(stat, 92, String.valueOf(hojaConsultaDTO.getDolorGarganta()));
        bindString(stat, 93, String.valueOf(hojaConsultaDTO.getAdenopatiasCervicales()));
        bindString(stat, 94, String.valueOf(hojaConsultaDTO.getExudado()));
        bindString(stat, 95, String.valueOf(hojaConsultaDTO.getPetequiasMucosa()));
        bindString(stat, 96, String.valueOf(hojaConsultaDTO.getSintomasUrinarios()));
        bindString(stat, 97, String.valueOf(hojaConsultaDTO.getLeucocituria()));
        bindString(stat, 98, String.valueOf(hojaConsultaDTO.getNitritos()));
        bindString(stat, 99, String.valueOf(hojaConsultaDTO.getEritrocitos()));
        bindString(stat, 100, String.valueOf(hojaConsultaDTO.getBilirrubinuria()));
        bindString(stat, 101, String.valueOf(hojaConsultaDTO.getObeso()));
        bindString(stat, 102, String.valueOf(hojaConsultaDTO.getSobrepeso()));
        bindString(stat, 103, String.valueOf(hojaConsultaDTO.getSospechaProblema()));
        bindString(stat, 104, String.valueOf(hojaConsultaDTO.getNormal()));
        bindString(stat, 105, String.valueOf(hojaConsultaDTO.getBajoPeso()));
        bindString(stat, 106, String.valueOf(hojaConsultaDTO.getBajoPesoSevero()));
        bindString(stat, 107, String.valueOf(hojaConsultaDTO.getTos()));
        bindString(stat, 108, String.valueOf(hojaConsultaDTO.getRinorrea()));
        bindString(stat, 109, String.valueOf(hojaConsultaDTO.getCongestionNasal()));
        bindString(stat, 110, String.valueOf(hojaConsultaDTO.getOtalgia()));
        bindString(stat, 111, String.valueOf(hojaConsultaDTO.getAleteoNasal()));
        bindString(stat, 112, String.valueOf(hojaConsultaDTO.getApnea()));
        bindString(stat, 113, String.valueOf(hojaConsultaDTO.getRespiracionRapida()));
        bindString(stat, 114, String.valueOf(hojaConsultaDTO.getQuejidoEspiratorio()));
        bindString(stat, 115, String.valueOf(hojaConsultaDTO.getEstiradorReposo()));
        bindString(stat, 116, String.valueOf(hojaConsultaDTO.getTirajeSubcostal()));
        bindString(stat, 117, String.valueOf(hojaConsultaDTO.getSibilancias()));
        bindString(stat, 118, String.valueOf(hojaConsultaDTO.getCrepitos()));
        bindString(stat, 119, String.valueOf(hojaConsultaDTO.getRoncos()));
        bindString(stat, 120, String.valueOf(hojaConsultaDTO.getOtraFif()));
        bindString(stat, 121, hojaConsultaDTO.getNuevaFif());
        bindString(stat, 122, String.valueOf(hojaConsultaDTO.getInterconsultaPediatrica()));
        bindString(stat, 123, String.valueOf(hojaConsultaDTO.getReferenciaHospital()));
        bindString(stat, 124, String.valueOf(hojaConsultaDTO.getReferenciaDengue()));
        bindString(stat, 125, String.valueOf(hojaConsultaDTO.getReferenciaIrag()));
        bindString(stat, 126, String.valueOf(hojaConsultaDTO.getReferenciaChik()));
        bindString(stat, 127, String.valueOf(hojaConsultaDTO.getEti()));
        bindString(stat, 128, String.valueOf(hojaConsultaDTO.getIrag()));
        bindString(stat, 129, String.valueOf(hojaConsultaDTO.getNeumonia()));
        bindString(stat, 130, String.valueOf(hojaConsultaDTO.getLactanciaMaterna()));
        bindString(stat, 131, String.valueOf(hojaConsultaDTO.getVacunasCompletas()));
        bindString(stat, 132, String.valueOf(hojaConsultaDTO.getVacunaInfluenza()));
        bindString(stat, 133, hojaConsultaDTO.getFechaVacuna());
        bindInteger(stat, 134, hojaConsultaDTO.getSaturaciono2());
        bindDouble(stat, 135,  hojaConsultaDTO.getImc());
        bindString(stat, 136, hojaConsultaDTO.getCategoria());
        bindString(stat, 137, String.valueOf(hojaConsultaDTO.getCambioCategoria()));
        bindString(stat, 138, String.valueOf(hojaConsultaDTO.getManifestacionHemorragica()));
        bindString(stat, 139, String.valueOf(hojaConsultaDTO.getPruebaTorniquetePositiva()));
        bindString(stat, 140, String.valueOf(hojaConsultaDTO.getPetequia10Pt()));
        bindString(stat, 141, String.valueOf(hojaConsultaDTO.getPetequia20Pt()));
        bindString(stat, 142, String.valueOf(hojaConsultaDTO.getPielExtremidadesFrias()));
        bindString(stat, 143, String.valueOf(hojaConsultaDTO.getPalidezEnExtremidades()));
        bindString(stat, 144, String.valueOf(hojaConsultaDTO.getEpistaxis()));
        bindString(stat, 145, String.valueOf(hojaConsultaDTO.getGingivorragia()));
        bindString(stat, 146, String.valueOf(hojaConsultaDTO.getPetequiasEspontaneas()));
        bindString(stat, 147, String.valueOf(hojaConsultaDTO.getLlenadoCapilar2seg()));
        bindString(stat, 148, String.valueOf(hojaConsultaDTO.getCianosis()));
        bindString(stat, 149, String.valueOf(hojaConsultaDTO.getLinfocitosaAtipicos()));
        bindString(stat, 150, hojaConsultaDTO.getFechaLinfocitos());
        bindString(stat, 151, String.valueOf(hojaConsultaDTO.getHipermenorrea()));
        bindString(stat, 152, String.valueOf(hojaConsultaDTO.getHematemesis()));
        bindString(stat, 153, String.valueOf(hojaConsultaDTO.getMelena()));
        bindString(stat, 154, String.valueOf(hojaConsultaDTO.getHemoconc()));
        bindString(stat, 153, String.valueOf(hojaConsultaDTO.getHemoconcentracion())); //dato  de tipo short
        bindString(stat, 156, String.valueOf(hojaConsultaDTO.getHospitalizado()));
        bindString(stat, 157, hojaConsultaDTO.getHospitalizadoEspecificar());
        bindString(stat, 158, String.valueOf(hojaConsultaDTO.getTransfusionSangre()));
        bindString(stat, 159, hojaConsultaDTO.getTransfusionEspecificar());
        bindString(stat, 160, String.valueOf(hojaConsultaDTO.getTomandoMedicamento()));
        bindString(stat, 161, hojaConsultaDTO.getMedicamentoEspecificar());
        bindString(stat, 162, String.valueOf(hojaConsultaDTO.getMedicamentoDistinto()));
        bindString(stat, 163, hojaConsultaDTO.getMedicamentoDistEspecificar());
        bindString(stat, 164, hojaConsultaDTO.getHorasv());
        bindString(stat, 165, String.valueOf(hojaConsultaDTO.getAcetaminofen()));
        bindString(stat, 166, String.valueOf(hojaConsultaDTO.getAsa()));
        bindString(stat, 167, String.valueOf(hojaConsultaDTO.getIbuprofen()));
        bindString(stat, 168, String.valueOf(hojaConsultaDTO.getPenicilina()));
        bindString(stat, 169, String.valueOf(hojaConsultaDTO.getAmoxicilina()));
        bindString(stat, 170, String.valueOf(hojaConsultaDTO.getDicloxacilina()));
        bindString(stat, 171, hojaConsultaDTO.getOtroAntibiotico());
        bindString(stat, 172, String.valueOf(hojaConsultaDTO.getFurazolidona()));
        bindString(stat, 173, String.valueOf(hojaConsultaDTO.getMetronidazolTinidazol()));
        bindString(stat, 174, String.valueOf(hojaConsultaDTO.getAlbendazolMebendazol()));
        bindString(stat, 175, String.valueOf(hojaConsultaDTO.getSulfatoFerroso()));
        bindString(stat, 176, String.valueOf(hojaConsultaDTO.getSueroOral()));
        bindString(stat, 177, String.valueOf(hojaConsultaDTO.getSulfatoZinc()));
        bindString(stat, 178, String.valueOf(hojaConsultaDTO.getLiquidosIv()));
        bindString(stat, 179, String.valueOf(hojaConsultaDTO.getPrednisona()));
        bindString(stat, 180, String.valueOf(hojaConsultaDTO.getHidrocortisonaIv()));
        bindString(stat, 181, String.valueOf(hojaConsultaDTO.getSalbutamol()));
        bindString(stat, 182, String.valueOf(hojaConsultaDTO.getOseltamivir()));
        bindLong(stat, 183, hojaConsultaDTO.getTelef());
        bindString(stat, 184, hojaConsultaDTO.getProximaCita());
        bindString(stat, 185, String.valueOf(hojaConsultaDTO.getHorarioClases()));
        bindString(stat, 186, hojaConsultaDTO.getColegio());
        bindString(stat, 187, String.valueOf(hojaConsultaDTO.getBhc()));
        bindString(stat, 188, String.valueOf(hojaConsultaDTO.getSerologiaDengue()));
        bindString(stat, 189, String.valueOf(hojaConsultaDTO.getSerologiaChik()));
        bindString(stat, 190, String.valueOf(hojaConsultaDTO.getGotaGruesa()));
        bindString(stat, 191, String.valueOf(hojaConsultaDTO.getExtendidoPeriferico()));
        bindString(stat, 192, String.valueOf(hojaConsultaDTO.getEgo()));
        bindString(stat, 193, String.valueOf(hojaConsultaDTO.getEgh()));
        bindString(stat, 194, String.valueOf(hojaConsultaDTO.getCitologiaFecal()));
        bindString(stat, 195, String.valueOf(hojaConsultaDTO.getFactorReumatoideo()));
        bindString(stat, 196, String.valueOf(hojaConsultaDTO.getAlbumina()));
        bindString(stat, 197, String.valueOf(hojaConsultaDTO.getAstAlt()));
        bindString(stat, 198, String.valueOf(hojaConsultaDTO.getBilirrubinas()));
        bindString(stat, 199, String.valueOf(hojaConsultaDTO.getCpk()));
        bindString(stat, 200, String.valueOf(hojaConsultaDTO.getColesterol()));
        bindString(stat, 201, String.valueOf(hojaConsultaDTO.getInfluenza()));
        bindString(stat, 202, hojaConsultaDTO.getOtroExamenLab());
        bindString(stat, 203, String.valueOf(hojaConsultaDTO.getOel()));
        bindInteger(stat,204, hojaConsultaDTO.getNumOrdenLaboratorio());
        bindString(stat, 205, hojaConsultaDTO.getFechaOrdenLaboratorio());
        bindString(stat, 206, String.valueOf(hojaConsultaDTO.getDiagnostico1()));  //dato  de tipo short
        bindString(stat, 207, String.valueOf(hojaConsultaDTO.getDiagnostico2()));  //dato  de tipo short
        bindString(stat, 208, String.valueOf(hojaConsultaDTO.getDiagnostico3()));  //dato  de tipo short
        bindString(stat, 209, String.valueOf(hojaConsultaDTO.getDiagnostico4()));  //dato  de tipo short
        bindString(stat, 210, hojaConsultaDTO.getOtroDiagnostico());
        bindString(stat, 211, hojaConsultaDTO.getFechaCierre());
        bindString(stat, 212, hojaConsultaDTO.getFechaCambioTurno());
        bindString(stat, 213, hojaConsultaDTO.getFechaCierreCambioTurno());
        bindString(stat, 214, String.valueOf(hojaConsultaDTO.getUsuarioMedico())); //dato  de tipo short
        bindString(stat, 215, String.valueOf(hojaConsultaDTO.getMedicoCambioTurno())); //dato  de tipo short
        bindString(stat, 216, String.valueOf(hojaConsultaDTO.getOtro()));
        bindString(stat, 217, hojaConsultaDTO.getEstudiosParticipantes());
        bindString(stat, 218, String.valueOf(hojaConsultaDTO.getcV()));
        bindString(stat, 219, String.valueOf(hojaConsultaDTO.getConsultaRespiratorio()));
        bindString(stat, 220, String.valueOf(hojaConsultaDTO.getEsConsultaTerreno()));
        bindString(stat, 221, String.valueOf(hojaConsultaDTO.getEstadoCarga()));
        bindString(stat, 222, String.valueOf(hojaConsultaDTO.getHora()));
        bindString(stat, 223, String.valueOf(hojaConsultaDTO.getNoAtiendeLlamadoEnfermeria()));
        bindString(stat, 224, String.valueOf(hojaConsultaDTO.getNoAtiendeLlamadoMedico()));
        bindString(stat, 225, hojaConsultaDTO.getStatusSubmitted());
    }

    @SuppressLint("Range")
    public static InicioDTO crearListaConsulta(Cursor cursor) {
        InicioDTO mInicioDTO = new InicioDTO();
        mInicioDTO.setSecHojaConsulta(cursor.getInt(cursor.getColumnIndex(MainDBConstants.secHojaConsulta)));
        mInicioDTO.setCodExpediente(cursor.getInt(cursor.getColumnIndex(MainDBConstants.codExpediente)));
        mInicioDTO.setNumHojaConsulta(cursor.getInt(cursor.getColumnIndex(MainDBConstants.numHojaConsulta)));
        mInicioDTO.setNomPaciente(cursor.getString(cursor.getColumnIndex(MainDBConstants.nombrePaciente)));
        mInicioDTO.setDescripcion(cursor.getString(cursor.getColumnIndex(MainDBConstants.descripcion)));
        mInicioDTO.setEstado(cursor.getString(cursor.getColumnIndex(MainDBConstants.estado)));
        mInicioDTO.setSexo(cursor.getString(cursor.getColumnIndex(MainDBConstants.sexo)));
        mInicioDTO.setFechaNac(cursor.getString(cursor.getColumnIndex(MainDBConstants.fechaNac)));
        mInicioDTO.setFechaConsulta(cursor.getString(cursor.getColumnIndex(MainDBConstants.fechaConsulta)));
        mInicioDTO.setNumOrdenLlegada(cursor.getString(cursor.getColumnIndex(MainDBConstants.ordenLlegada)));
        mInicioDTO.setCodigoEstado((char) cursor.getInt(cursor.getColumnIndex(MainDBConstants.codigo)));
        mInicioDTO.setNombreMedico(cursor.getString(cursor.getColumnIndex(MainDBConstants.nombre)));
        mInicioDTO.setUsuarioEnfermeria(cursor.getString(cursor.getColumnIndex(MainDBConstants.usuarioEnfermeria)));
        mInicioDTO.setUsuarioMedico(cursor.getInt(cursor.getColumnIndex(MainDBConstants.usuarioMedico)));
        mInicioDTO.setHorasv(cursor.getString(cursor.getColumnIndex(MainDBConstants.horasv)));
        mInicioDTO.setPesoKg(cursor.getString(cursor.getColumnIndex(MainDBConstants.pesoKg)));
        mInicioDTO.setTallaCm(cursor.getString(cursor.getColumnIndex(MainDBConstants.tallaCm)));
        mInicioDTO.setTemperatura(cursor.getString(cursor.getColumnIndex(MainDBConstants.temperaturac)));
        /*mInicioDTO.setExpedienteFisico(cursor.getString(cursor.getColumnIndex(MainDBConstants.expedienteFisico)));
        mInicioDTO.setMedicoCambioTurno(cursor.getInt(cursor.getColumnIndex(MainDBConstants.medicoCambioTurno)));
        mInicioDTO.setNombreMedico(cursor.getString(cursor.getColumnIndex(MainDBConstants.usuarioMedico)));
        mInicioDTO.setEstudiosParticipantes(cursor.getString(cursor.getColumnIndex(MainDBConstants.estudiosParticipantes)));
        mInicioDTO.setCategoria(cursor.getString(cursor.getColumnIndex(MainDBConstants.categoria)));
        mInicioDTO.setFif(cursor.getString(cursor.getColumnIndex(MainDBConstants.fif)));
        mInicioDTO.setConsulta(cursor.getString(cursor.getColumnIndex(MainDBConstants.consulta)));
        mInicioDTO.setTemMedc(cursor.getString(cursor.getColumnIndex(MainDBConstants.temMedc)));
        mInicioDTO.setFciaResp(cursor.getString(cursor.getColumnIndex(MainDBConstants.fciaResp)));
        mInicioDTO.setConsultaRespiratoria(cursor.getString(cursor.getColumnIndex(MainDBConstants.consultaRespiratorio)));*/
        return mInicioDTO;
    }

    @SuppressLint("Range")
    public static ExpedienteDTO crearListaExpediente(Cursor cursor) {
        ExpedienteDTO mExpediente = new ExpedienteDTO();
        mExpediente.setNumHojaConsulta(cursor.getInt(cursor.getColumnIndex(MainDBConstants.numHojaConsulta)));
        mExpediente.setFechaCierre(cursor.getString(cursor.getColumnIndex(MainDBConstants.fechaCierre)));
        mExpediente.setSecHojaConsulta(cursor.getInt(cursor.getColumnIndex(MainDBConstants.secHojaConsulta)));
        mExpediente.setDescripcion(cursor.getString(cursor.getColumnIndex(MainDBConstants.descripcion)));
        mExpediente.setNombre(cursor.getString(cursor.getColumnIndex(MainDBConstants.nombre)));
        mExpediente.setHoraCierre(cursor.getString(cursor.getColumnIndex(MainDBConstants.fechaCierre)));
        return mExpediente;
    }

    public static ContentValues crearHojaConsultaValues(HojaConsultaOffLineDTO hojaConsultaOffLineDTO){
        ContentValues cv = new ContentValues();
        //cv.put(MainDBConstants.secHojaConsulta, hojaConsultaOffLineDTO.getSecHojaConsulta());
        cv.put(MainDBConstants.codExpediente, hojaConsultaOffLineDTO.getCodExpediente());
        cv.put(MainDBConstants.numHojaConsulta, hojaConsultaOffLineDTO.getNumHojaConsulta());
        cv.put(MainDBConstants.ordenLlegada, hojaConsultaOffLineDTO.getNumOrdenLlegada());
        cv.put(MainDBConstants.estado, hojaConsultaOffLineDTO.getEstado());
        if (hojaConsultaOffLineDTO.getFechaConsulta() != null)
            cv.put(MainDBConstants.fechaConsulta, hojaConsultaOffLineDTO.getFechaConsulta());
        cv.put(MainDBConstants.pesoKg, hojaConsultaOffLineDTO.getPesoKg());
        cv.put(MainDBConstants.tallaCm, hojaConsultaOffLineDTO.getTallaCm());
        cv.put(MainDBConstants.temperaturac, hojaConsultaOffLineDTO.getTemperaturac());
        cv.put(MainDBConstants.usuarioEnfermeria, hojaConsultaOffLineDTO.getUsuarioEnfermeria());
        cv.put(MainDBConstants.expedienteFisico, hojaConsultaOffLineDTO.getExpedienteFisico());
        cv.put(MainDBConstants.historiaExamenFisico, hojaConsultaOffLineDTO.getHistoriaExamenFisico());
        cv.put(MainDBConstants.planes, hojaConsultaOffLineDTO.getPlanes());
        cv.put(MainDBConstants.presion, hojaConsultaOffLineDTO.getPresion());
        cv.put(MainDBConstants.pas, hojaConsultaOffLineDTO.getPas());
        cv.put(MainDBConstants.pad, hojaConsultaOffLineDTO.getPad());
        cv.put(MainDBConstants.fciaResp, hojaConsultaOffLineDTO.getFciaResp());
        cv.put(MainDBConstants.fciaCard, hojaConsultaOffLineDTO.getFciaCard());
        cv.put(MainDBConstants.lugarAtencion, hojaConsultaOffLineDTO.getLugarAtencion());
        cv.put(MainDBConstants.consulta, hojaConsultaOffLineDTO.getConsulta());
        cv.put(MainDBConstants.segChick, hojaConsultaOffLineDTO.getSegChick());
        cv.put(MainDBConstants.turno, hojaConsultaOffLineDTO.getTurno());
        cv.put(MainDBConstants.temMedc, hojaConsultaOffLineDTO.getTemMedc());
        cv.put(MainDBConstants.fis, hojaConsultaOffLineDTO.getFis());
        cv.put(MainDBConstants.fif, hojaConsultaOffLineDTO.getFif());
        cv.put(MainDBConstants.ultDiaFiebre, hojaConsultaOffLineDTO.getUltDiaFiebre());
        cv.put(MainDBConstants.ultDosisAntipiretico, hojaConsultaOffLineDTO.getUltDosisAntipiretico());
        cv.put(MainDBConstants.amPmUltDiaFiebre, hojaConsultaOffLineDTO.getAmPmUltDiaFiebre());
        cv.put(MainDBConstants.horaUltDosisAntipiretico, hojaConsultaOffLineDTO.getHoraUltDosisAntipiretico());
        cv.put(MainDBConstants.amPmUltDosisAntipiretico, hojaConsultaOffLineDTO.getAmPmUltDosisAntipiretico());
        cv.put(MainDBConstants.fiebre, hojaConsultaOffLineDTO.getFiebre());
        cv.put(MainDBConstants.astenia, hojaConsultaOffLineDTO.getAstenia());
        cv.put(MainDBConstants.asomnoliento, hojaConsultaOffLineDTO.getAsomnoliento());
        cv.put(MainDBConstants.malEstado, hojaConsultaOffLineDTO.getMalEstado());
        cv.put(MainDBConstants.perdidaConsciencia, hojaConsultaOffLineDTO.getPerdidaConsciencia());
        cv.put(MainDBConstants.inquieto, hojaConsultaOffLineDTO.getInquieto());
        cv.put(MainDBConstants.convulsiones, hojaConsultaOffLineDTO.getConvulsiones());
        cv.put(MainDBConstants.hipotermia, hojaConsultaOffLineDTO.getHipotermia());
        cv.put(MainDBConstants.letargia, hojaConsultaOffLineDTO.getLetargia());
        cv.put(MainDBConstants.pocoApetito, hojaConsultaOffLineDTO.getPocoApetito());
        cv.put(MainDBConstants.nausea, hojaConsultaOffLineDTO.getNausea());
        cv.put(MainDBConstants.dificultadAlimentarse, hojaConsultaOffLineDTO.getDificultadAlimentarse());
        cv.put(MainDBConstants.vomito12horas, hojaConsultaOffLineDTO.getVomito12horas());
        cv.put(MainDBConstants.vomito12h, hojaConsultaOffLineDTO.getVomito12h());
        cv.put(MainDBConstants.diarrea, hojaConsultaOffLineDTO.getDiarrea());
        cv.put(MainDBConstants.diarreaSangre, hojaConsultaOffLineDTO.getDiarreaSangre());
        cv.put(MainDBConstants.estrenimiento, hojaConsultaOffLineDTO.getEstrenimiento());
        cv.put(MainDBConstants.dolorAbIntermitente, hojaConsultaOffLineDTO.getDolorAbIntermitente());
        cv.put(MainDBConstants.dolorAbContinuo, hojaConsultaOffLineDTO.getDolorAbContinuo());
        cv.put(MainDBConstants.epigastralgia, hojaConsultaOffLineDTO.getEpigastralgia());
        cv.put(MainDBConstants.intoleranciaOral, hojaConsultaOffLineDTO.getIntoleranciaOral());
        cv.put(MainDBConstants.distensionAbdominal, hojaConsultaOffLineDTO.getDistensionAbdominal());
        cv.put(MainDBConstants.hepatomegalia, hojaConsultaOffLineDTO.getHepatomegalia());
        cv.put(MainDBConstants.hepatomegaliaCm, hojaConsultaOffLineDTO.getHepatomegaliaCm());
        cv.put(MainDBConstants.altralgia, hojaConsultaOffLineDTO.getAltralgia());
        cv.put(MainDBConstants.mialgia, hojaConsultaOffLineDTO.getMialgia());
        cv.put(MainDBConstants.lumbalgia, hojaConsultaOffLineDTO.getLumbalgia());
        cv.put(MainDBConstants.dolorCuello, hojaConsultaOffLineDTO.getDolorCuello());
        cv.put(MainDBConstants.tenosinovitis, hojaConsultaOffLineDTO.getTenosinovitis());
        cv.put(MainDBConstants.artralgiaProximal, hojaConsultaOffLineDTO.getArtralgiaProximal());
        cv.put(MainDBConstants.artralgiaDistal, hojaConsultaOffLineDTO.getArtralgiaDistal());
        cv.put(MainDBConstants.conjuntivitis, hojaConsultaOffLineDTO.getConjuntivitis());
        cv.put(MainDBConstants.edemaMunecas, hojaConsultaOffLineDTO.getEdemaMunecas());
        cv.put(MainDBConstants.edemaCodos, hojaConsultaOffLineDTO.getEdemaCodos());
        cv.put(MainDBConstants.edemaHombros, hojaConsultaOffLineDTO.getEdemaHombros());
        cv.put(MainDBConstants.edemaRodillas, hojaConsultaOffLineDTO.getEdemaRodillas());
        cv.put(MainDBConstants.edemaTobillos, hojaConsultaOffLineDTO.getEdemaTobillos());
        cv.put(MainDBConstants.cefalea, hojaConsultaOffLineDTO.getCefalea());
        cv.put(MainDBConstants.rigidezCuello, hojaConsultaOffLineDTO.getRigidezCuello());
        cv.put(MainDBConstants.inyeccionConjuntival, hojaConsultaOffLineDTO.getInyeccionConjuntival());
        cv.put(MainDBConstants.hemorragiaSuconjuntival, hojaConsultaOffLineDTO.getHemorragiaSuconjuntival());
        cv.put(MainDBConstants.dolorRetroocular, hojaConsultaOffLineDTO.getDolorRetroocular());
        cv.put(MainDBConstants.fontanelaAbombada, hojaConsultaOffLineDTO.getFontanelaAbombada());
        cv.put(MainDBConstants.ictericiaConuntival, hojaConsultaOffLineDTO.getIctericiaConuntival());
        cv.put(MainDBConstants.lenguaMucosasSecas, hojaConsultaOffLineDTO.getLenguaMucosasSecas());
        cv.put(MainDBConstants.pliegueCutaneo, hojaConsultaOffLineDTO.getPliegueCutaneo());
        cv.put(MainDBConstants.orinaReducida, hojaConsultaOffLineDTO.getOrinaReducida());
        cv.put(MainDBConstants.bebeConSed, hojaConsultaOffLineDTO.getBebeConSed());
        cv.put(MainDBConstants.ojosHundidos, hojaConsultaOffLineDTO.getOjosHundidos());
        cv.put(MainDBConstants.fontanelaHundida, hojaConsultaOffLineDTO.getFontanelaHundida());
        cv.put(MainDBConstants.rahsLocalizado, hojaConsultaOffLineDTO.getRahsLocalizado());
        cv.put(MainDBConstants.rahsGeneralizado, hojaConsultaOffLineDTO.getRahsGeneralizado());
        cv.put(MainDBConstants.rashEritematoso, hojaConsultaOffLineDTO.getRashEritematoso());
        cv.put(MainDBConstants.rahsMacular, hojaConsultaOffLineDTO.getRahsMacular());
        cv.put(MainDBConstants.rashPapular, hojaConsultaOffLineDTO.getRashPapular());
        cv.put(MainDBConstants.rahsMoteada, hojaConsultaOffLineDTO.getRahsMoteada());
        cv.put(MainDBConstants.ruborFacial, hojaConsultaOffLineDTO.getRuborFacial());
        cv.put(MainDBConstants.equimosis, hojaConsultaOffLineDTO.getEquimosis());
        cv.put(MainDBConstants.cianosisCentral, hojaConsultaOffLineDTO.getCianosisCentral());
        cv.put(MainDBConstants.ictericia, hojaConsultaOffLineDTO.getIctericia());
        cv.put(MainDBConstants.eritema, hojaConsultaOffLineDTO.getEritema());
        cv.put(MainDBConstants.dolorGarganta, hojaConsultaOffLineDTO.getDolorGarganta());
        cv.put(MainDBConstants.adenopatiasCervicales, hojaConsultaOffLineDTO.getAdenopatiasCervicales());
        cv.put(MainDBConstants.exudado, hojaConsultaOffLineDTO.getExudado());
        cv.put(MainDBConstants.petequiasMucosa, hojaConsultaOffLineDTO.getPetequiasMucosa());
        cv.put(MainDBConstants.sintomasUrinarios, hojaConsultaOffLineDTO.getSintomasUrinarios());
        cv.put(MainDBConstants.leucocituria, hojaConsultaOffLineDTO.getLeucocituria());
        cv.put(MainDBConstants.nitritos, hojaConsultaOffLineDTO.getNitritos());
        cv.put(MainDBConstants.eritrocitos, hojaConsultaOffLineDTO.getEritrocitos());
        cv.put(MainDBConstants.bilirrubinuria, hojaConsultaOffLineDTO.getBilirrubinuria());
        cv.put(MainDBConstants.obeso, hojaConsultaOffLineDTO.getObeso());
        cv.put(MainDBConstants.sobrepeso, hojaConsultaOffLineDTO.getSobrepeso());
        cv.put(MainDBConstants.sospechaProblema, hojaConsultaOffLineDTO.getSospechaProblema());
        cv.put(MainDBConstants.normal, hojaConsultaOffLineDTO.getNormal());
        cv.put(MainDBConstants.bajoPeso, hojaConsultaOffLineDTO.getBajoPeso());
        cv.put(MainDBConstants.bajoPesoSevero, hojaConsultaOffLineDTO.getBajoPesoSevero());
        cv.put(MainDBConstants.tos, hojaConsultaOffLineDTO.getTos());
        cv.put(MainDBConstants.rinorrea, hojaConsultaOffLineDTO.getRinorrea());
        cv.put(MainDBConstants.congestionNasal, hojaConsultaOffLineDTO.getCongestionNasal());
        cv.put(MainDBConstants.otalgia, hojaConsultaOffLineDTO.getOtalgia());
        cv.put(MainDBConstants.aleteoNasal, hojaConsultaOffLineDTO.getAleteoNasal());
        cv.put(MainDBConstants.apnea, hojaConsultaOffLineDTO.getApnea());
        cv.put(MainDBConstants.respiracionRapida, hojaConsultaOffLineDTO.getRespiracionRapida());
        cv.put(MainDBConstants.quejidoEspiratorio, hojaConsultaOffLineDTO.getQuejidoEspiratorio());
        cv.put(MainDBConstants.estiradorReposo, hojaConsultaOffLineDTO.getEstiradorReposo());
        cv.put(MainDBConstants.tirajeSubcostal, hojaConsultaOffLineDTO.getTirajeSubcostal());
        cv.put(MainDBConstants.sibilancias, hojaConsultaOffLineDTO.getSibilancias());
        cv.put(MainDBConstants.crepitos, hojaConsultaOffLineDTO.getCrepitos());
        cv.put(MainDBConstants.roncos, hojaConsultaOffLineDTO.getRoncos());
        cv.put(MainDBConstants.otraFif, hojaConsultaOffLineDTO.getOtraFif());
        cv.put(MainDBConstants.nuevaFif, hojaConsultaOffLineDTO.getNuevaFif());
        cv.put(MainDBConstants.interconsultaPediatrica, hojaConsultaOffLineDTO.getInterconsultaPediatrica());
        cv.put(MainDBConstants.referenciaHospital, hojaConsultaOffLineDTO.getReferenciaHospital());
        cv.put(MainDBConstants.referenciaDengue, hojaConsultaOffLineDTO.getReferenciaDengue());
        cv.put(MainDBConstants.referenciaIrag, hojaConsultaOffLineDTO.getReferenciaIrag());
        cv.put(MainDBConstants.referenciaChik, hojaConsultaOffLineDTO.getReferenciaChik());
        cv.put(MainDBConstants.eti, hojaConsultaOffLineDTO.getEti());
        cv.put(MainDBConstants.irag, hojaConsultaOffLineDTO.getIrag());
        cv.put(MainDBConstants.neumonia, hojaConsultaOffLineDTO.getNeumonia());
        cv.put(MainDBConstants.lactanciaMaterna, hojaConsultaOffLineDTO.getLactanciaMaterna());
        cv.put(MainDBConstants.vacunasCompletas, hojaConsultaOffLineDTO.getVacunasCompletas());
        cv.put(MainDBConstants.vacunaInfluenza, hojaConsultaOffLineDTO.getVacunaInfluenza());
        if (hojaConsultaOffLineDTO.getFechaVacuna() != null)
            cv.put(MainDBConstants.fechaVacuna, hojaConsultaOffLineDTO.getFechaVacuna());
        cv.put(MainDBConstants.saturaciono2, hojaConsultaOffLineDTO.getSaturaciono2());
        cv.put(MainDBConstants.imc, hojaConsultaOffLineDTO.getImc());
        cv.put(MainDBConstants.categoria, hojaConsultaOffLineDTO.getCategoria());
        cv.put(MainDBConstants.cambioCategoria, hojaConsultaOffLineDTO.getCambioCategoria());
        cv.put(MainDBConstants.manifestacionHemorragica, hojaConsultaOffLineDTO.getManifestacionHemorragica());
        cv.put(MainDBConstants.pruebaTorniquetePositiva, hojaConsultaOffLineDTO.getPruebaTorniquetePositiva());
        cv.put(MainDBConstants.petequia10Pt, hojaConsultaOffLineDTO.getPetequia10Pt());
        cv.put(MainDBConstants.petequia20Pt, hojaConsultaOffLineDTO.getPetequia20Pt());
        cv.put(MainDBConstants.pielExtremidadesFrias, hojaConsultaOffLineDTO.getPielExtremidadesFrias());
        cv.put(MainDBConstants.palidezEnExtremidades, hojaConsultaOffLineDTO.getPalidezEnExtremidades());
        cv.put(MainDBConstants.epistaxis, hojaConsultaOffLineDTO.getEpistaxis());
        cv.put(MainDBConstants.gingivorragia, hojaConsultaOffLineDTO.getGingivorragia());
        cv.put(MainDBConstants.petequiasEspontaneas, hojaConsultaOffLineDTO.getPetequiasEspontaneas());
        cv.put(MainDBConstants.llenadoCapilar2seg, hojaConsultaOffLineDTO.getLlenadoCapilar2seg());
        cv.put(MainDBConstants.cianosis, hojaConsultaOffLineDTO.getCianosis());
        cv.put(MainDBConstants.linfocitosaAtipicos, hojaConsultaOffLineDTO.getLinfocitosaAtipicos());
        if (hojaConsultaOffLineDTO.getFechaLinfocitos() != null)
            cv.put(MainDBConstants.fechaLinfocitos, hojaConsultaOffLineDTO.getFechaLinfocitos());
        cv.put(MainDBConstants.hipermenorrea, hojaConsultaOffLineDTO.getHipermenorrea());
        cv.put(MainDBConstants.hematemesis, hojaConsultaOffLineDTO.getHematemesis());
        cv.put(MainDBConstants.melena, hojaConsultaOffLineDTO.getMelena());
        cv.put(MainDBConstants.hemoconc, hojaConsultaOffLineDTO.getHemoconc());
        cv.put(MainDBConstants.hemoconcentracion, hojaConsultaOffLineDTO.getHemoconcentracion());
        cv.put(MainDBConstants.hospitalizado, hojaConsultaOffLineDTO.getHospitalizado());
        cv.put(MainDBConstants.hospitalizadoEspecificar, hojaConsultaOffLineDTO.getHospitalizadoEspecificar());
        cv.put(MainDBConstants.transfusionSangre, hojaConsultaOffLineDTO.getTransfusionSangre());
        cv.put(MainDBConstants.transfusionEspecificar, hojaConsultaOffLineDTO.getTransfusionEspecificar());
        cv.put(MainDBConstants.tomandoMedicamento, hojaConsultaOffLineDTO.getTomandoMedicamento());
        cv.put(MainDBConstants.medicamentoEspecificar, hojaConsultaOffLineDTO.getMedicamentoEspecificar());
        cv.put(MainDBConstants.medicamentoDistinto, hojaConsultaOffLineDTO.getMedicamentoDistinto());
        cv.put(MainDBConstants.medicamentoDistEspecificar, hojaConsultaOffLineDTO.getMedicamentoDistEspecificar());
        cv.put(MainDBConstants.horasv, hojaConsultaOffLineDTO.getHorasv());
        cv.put(MainDBConstants.acetaminofen, hojaConsultaOffLineDTO.getAcetaminofen());
        cv.put(MainDBConstants.asa, hojaConsultaOffLineDTO.getAsa());
        cv.put(MainDBConstants.ibuprofen, hojaConsultaOffLineDTO.getIbuprofen());
        cv.put(MainDBConstants.penicilina, hojaConsultaOffLineDTO.getPenicilina());
        cv.put(MainDBConstants.amoxicilina, hojaConsultaOffLineDTO.getAmoxicilina());
        cv.put(MainDBConstants.dicloxacilina, hojaConsultaOffLineDTO.getDicloxacilina());
        cv.put(MainDBConstants.otroAntibiotico, hojaConsultaOffLineDTO.getOtroAntibiotico());
        cv.put(MainDBConstants.furazolidona, hojaConsultaOffLineDTO.getFurazolidona());
        cv.put(MainDBConstants.metronidazolTinidazol, hojaConsultaOffLineDTO.getMetronidazolTinidazol());
        cv.put(MainDBConstants.albendazolMebendazol, hojaConsultaOffLineDTO.getAlbendazolMebendazol());
        cv.put(MainDBConstants.sulfatoFerroso, hojaConsultaOffLineDTO.getSulfatoFerroso());
        cv.put(MainDBConstants.sueroOral, hojaConsultaOffLineDTO.getSueroOral());
        cv.put(MainDBConstants.sulfatoZinc, hojaConsultaOffLineDTO.getSulfatoZinc());
        cv.put(MainDBConstants.liquidosIv, hojaConsultaOffLineDTO.getLiquidosIv());
        cv.put(MainDBConstants.prednisona, hojaConsultaOffLineDTO.getPrednisona());
        cv.put(MainDBConstants.hidrocortisonaIv, hojaConsultaOffLineDTO.getHidrocortisonaIv());
        cv.put(MainDBConstants.salbutamol, hojaConsultaOffLineDTO.getSalbutamol());
        cv.put(MainDBConstants.oseltamivir, hojaConsultaOffLineDTO.getOseltamivir());
        cv.put(MainDBConstants.telef, hojaConsultaOffLineDTO.getTelef());
        cv.put(MainDBConstants.proximaCita, hojaConsultaOffLineDTO.getProximaCita());
        cv.put(MainDBConstants.horarioClases, hojaConsultaOffLineDTO.getHorarioClases());
        cv.put(MainDBConstants.colegio, hojaConsultaOffLineDTO.getColegio());
        cv.put(MainDBConstants.bhc, hojaConsultaOffLineDTO.getBhc());
        cv.put(MainDBConstants.serologiaDengue, hojaConsultaOffLineDTO.getSerologiaDengue());
        cv.put(MainDBConstants.serologiaChik, hojaConsultaOffLineDTO.getSerologiaChik());
        cv.put(MainDBConstants.gotaGruesa, hojaConsultaOffLineDTO.getGotaGruesa());
        cv.put(MainDBConstants.extendidoPeriferico, hojaConsultaOffLineDTO.getExtendidoPeriferico());
        cv.put(MainDBConstants.ego, hojaConsultaOffLineDTO.getEgo());
        cv.put(MainDBConstants.egh, hojaConsultaOffLineDTO.getEgh());
        cv.put(MainDBConstants.citologiaFecal, hojaConsultaOffLineDTO.getCitologiaFecal());
        cv.put(MainDBConstants.factorReumatoideo, hojaConsultaOffLineDTO.getFactorReumatoideo());
        cv.put(MainDBConstants.albumina, hojaConsultaOffLineDTO.getAlbumina());
        cv.put(MainDBConstants.astAlt, hojaConsultaOffLineDTO.getAstAlt());
        cv.put(MainDBConstants.bilirrubinas, hojaConsultaOffLineDTO.getBilirrubinas());
        cv.put(MainDBConstants.cpk, hojaConsultaOffLineDTO.getCpk());
        cv.put(MainDBConstants.colesterol, hojaConsultaOffLineDTO.getColesterol());
        cv.put(MainDBConstants.influenza, hojaConsultaOffLineDTO.getInfluenza());
        cv.put(MainDBConstants.otroExamenLab, hojaConsultaOffLineDTO.getOtroExamenLab());
        cv.put(MainDBConstants.oel, hojaConsultaOffLineDTO.getOel());
        cv.put(MainDBConstants.numOrdenLaboratorio, hojaConsultaOffLineDTO.getNumOrdenLaboratorio());
        cv.put(MainDBConstants.fechaOrdenLaboratorio, hojaConsultaOffLineDTO.getFechaOrdenLaboratorio());
        if (hojaConsultaOffLineDTO.getDiagnostico1() > 0)
            cv.put(MainDBConstants.diagnostico1, hojaConsultaOffLineDTO.getDiagnostico1());
        if (hojaConsultaOffLineDTO.getDiagnostico2() > 0)
            cv.put(MainDBConstants.diagnostico2, hojaConsultaOffLineDTO.getDiagnostico2());
        if (hojaConsultaOffLineDTO.getDiagnostico3() > 0)
            cv.put(MainDBConstants.diagnostico3, hojaConsultaOffLineDTO.getDiagnostico3());
        if (hojaConsultaOffLineDTO.getDiagnostico4() > 0)
            cv.put(MainDBConstants.diagnostico4, hojaConsultaOffLineDTO.getDiagnostico4());
        if (hojaConsultaOffLineDTO.getOtroDiagnostico() != null)
            cv.put(MainDBConstants.otroDiagnostico, hojaConsultaOffLineDTO.getOtroDiagnostico());
        if (hojaConsultaOffLineDTO.getFechaCierre() != null)
            cv.put(MainDBConstants.fechaCierre, hojaConsultaOffLineDTO.getFechaCierre());
        if (hojaConsultaOffLineDTO.getFechaCambioTurno() != null)
            cv.put(MainDBConstants.fechaCambioTurno, hojaConsultaOffLineDTO.getFechaCierre());
        if (hojaConsultaOffLineDTO.getFechaCambioTurno() != null)
            cv.put(MainDBConstants.fechaCierreCambioTurno, hojaConsultaOffLineDTO.getFechaCambioTurno());
        cv.put(MainDBConstants.usuarioMedico, hojaConsultaOffLineDTO.getUsuarioMedico());
        cv.put(MainDBConstants.medicoCambioTurno, hojaConsultaOffLineDTO.getMedicoCambioTurno());
        cv.put(MainDBConstants.otro, hojaConsultaOffLineDTO.getOtro());
        cv.put(MainDBConstants.estudiosParticipantes, hojaConsultaOffLineDTO.getEstudiosParticipantes());
        cv.put(MainDBConstants.cV, hojaConsultaOffLineDTO.getcV());
        cv.put(MainDBConstants.consultaRespiratorio, hojaConsultaOffLineDTO.getConsultaRespiratorio());
        cv.put(MainDBConstants.esConsultaTerreno, hojaConsultaOffLineDTO.getEsConsultaTerreno());
        cv.put(MainDBConstants.estadoCarga, hojaConsultaOffLineDTO.getEstadoCarga());
        cv.put(MainDBConstants.hora, hojaConsultaOffLineDTO.getHora());
        cv.put(MainDBConstants.noAtiendeLlamadoEnfermeria, hojaConsultaOffLineDTO.getNoAtiendeLlamadoEnfermeria());
        cv.put(MainDBConstants.noAtiendeLlamadoMedico, hojaConsultaOffLineDTO.getNoAtiendeLlamadoMedico());
        cv.put(MainDBConstants.statusSubmitted, hojaConsultaOffLineDTO.getStatusSubmitted());
        return cv;
    }
}
